## cog
abc_cogOut:
  data:
    - { log: abc_cogOut, column: [0-2] }
st_originActCog:
  data:
    - { log: st_originActCog, column: [0-2] }
st_originRefCog:
  data:
    - { log: st_originRefCog, column: [0-2] }
## cog velocity
st_originActCogVel:
  data:
    - { log: st_originActCogVel, column: [0-2] }
st_originRefCogVel:
  data:
    - { log: st_originRefCogVel, column: [0-2] }
## zmp
abc_zmpOut:
  data:
    - { log: abc_zmpOut, column: [0-2] }
abc_refZmp:
  data:
    - { log: abc_refZmp, column: [0-2] }
st_originActZmp:
  data:
    - { log: st_originActZmp, column: [0-2] }
st_originRefZmp:
  data:
    - { log: st_originRefZmp, column: [0-2] }
st_originNewZmp:
  data:
    - { log: st_originNewZmp, column: [0-2] }
# root-link relative zmp
st_zmp:
  data:
    - { log: st_zmp, column: [0-2] }
## force
sh_rfsensorOut:
  data:
    - { log: sh_rfsensorOut, column: [0-5] }
sh_lfsensorOut:
  data:
    - { log: sh_lfsensorOut, column: [0-5] }
sh_rhsensorOut:
  data:
    - { log: sh_rhsensorOut, column: [0-5] }
sh_lhsensorOut:
  data:
    - { log: sh_lhsensorOut, column: [0-5] }
sh_vrthighsensorOut:
  data:
    - { log: sh_vrthighsensorOut, column: [0-5] }
sh_vlthighsensorOut:
  data:
    - { log: sh_vlthighsensorOut, column: [0-5] }
RobotHardware0_rfsensor:
  data:
    - { log: RobotHardware0_rfsensor, column: [0-5] }
RobotHardware0_lfsensor:
  data:
    - { log: RobotHardware0_lfsensor, column: [0-5] }
RobotHardware0_rhsensor:
  data:
    - { log: RobotHardware0_rhsensor, column: [0-5] }
RobotHardware0_lhsensor:
  data:
    - { log: RobotHardware0_lhsensor, column: [0-5] }
rmfo_off_rfsensor:
  func: plot_inverse
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }
rmfo_off_lfsensor:
  func: plot_inverse
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }
rmfo_off_rhsensor:
  data:
    - { log: rmfo_off_rhsensor, column: [0-5] }
rmfo_off_lhsensor:
  data:
    - { log: rmfo_off_lhsensor, column: [0-5] }
vs_off_vrthighsensor:
  func: plot_inverse
  data:
    - { log: vs_off_vrthighsensor, column: [0-5] }
vs_off_vlthighsensor:
  func: plot_inverse
  data:
    - { log: vs_off_vlthighsensor, column: [0-5] }
st_ref_rfsensor:
  data:
    - { log: st_allRefWrench, column: [0-5] }
st_ref_lfsensor:
  data:
    - { log: st_allRefWrench, column: [6-11] }
st_ref_rhsensor:
  data:
    - { log: st_allRefWrench, column: [12-17] }
st_ref_lhsensor:
  data:
    - { log: st_allRefWrench, column: [18-23] }
st_ref_vrthighsensor:
  data:
    - { log: st_allRefWrench, column: [24-29] }
st_ref_vlthighsensor:
  data:
    - { log: st_allRefWrench, column: [30-35] }
abc_rfsensor:
  data:
    - { log: abc_rfsensor, column: [0-2] }
abc_lfsensor:
  data:
    - { log: abc_lfsensor, column: [0-2] }
# comp
st_rfcomp:
  func: plot_comp
  data:
    - { log: st_allEEComp, column: [0-5] }
st_lfcomp:
  func: plot_comp
  data:
    - { log: st_allEEComp, column: [6-11] }
st_rhcomp:
  func: plot_comp
  data:
    - { log: st_allEEComp, column: [12-17] }
st_lhcomp:
  func: plot_comp
  data:
    - { log: st_allEEComp, column: [18-23] }
# imu
imu_gsensor:
  data:
    - { log: RobotHardware0_gsensor, column: [0-2] }
imu_gyrometer:
  func: plot_rad2deg
  data:
    - { log: RobotHardware0_gyrometer, column: [0-2] }
# rpy
sh_baseRpyOut:
  func: plot_rad2deg
  data:
    - { log: sh_baseRpyOut, column: [0-2] }
st_actBaseRpy:
  func: plot_rad2deg
  data:
    - { log: st_actBaseRpy, column: [0-2] }
st_currentBaseRpy:
  func: plot_rad2deg
  data:
    - { log: st_currentBaseRpy, column: [0-2] }
kf_rpy:
  func: plot_rad2deg
  data:
    - { log: kf_rpy, column: [0-2] }
sh_baseRpyVel:
  func: plot_rad2deg_vel
  data:
    - { log: sh_baseRpyOut, column: [0-2] }
st_currentBaseRpyVel:
  func: plot_rad2deg_vel
  data:
    - { log: st_currentBaseRpy, column: [0-2] }
st_actBaseRpyVel:
  func: plot_rad2deg_vel
  data:
    - { log: st_actBaseRpy, column: [0-2] }
# pos
abc_basePos:
  data:
    - { log: abc_baseTformOut, column: [0-2] }
st_currentBasePos:
  data:
    - { log: st_currentBasePos, column: [0-2] }
# optional data
abc_contactStates:
  data:
    - { log: abc_contactStates, column: [0-5] }
abc_controlSwingSupportTime:
  data:
    - { log: abc_controlSwingSupportTime, column: [0-5] }
# debug data
st_debugData:
  data:
    - { log: st_debugData, column:[0-5] }
# COP
sh_rfcop:
  data:
    - { log: sh_rfsensorOut, column: [0-5] }
  func: plot_COP
sh_lfcop:
  data:
    - { log: sh_lfsensorOut, column: [0-5] }
  func: plot_COP
st_rfcop:
  data:
    - { log: st_allRefWrench, column: [0-5] }
  func: plot_COP
st_lfcop:
  data:
    - { log: st_allRefWrench, column: [6-11] }
  func: plot_COP
rmfo_rfcop:
  data:
    - { log: rmfo_off_rfsensor, column: [0-5] }
  func: plot_COP
rmfo_lfcop:
  data:
    - { log: rmfo_off_lfsensor, column: [0-5] }
  func: plot_COP
sh_rhcop:
  data:
    - { log: sh_rhsensorOut, column: [0-5] }
  func: plot_COP
sh_lhcop:
  data:
    - { log: sh_lhsensorOut, column: [0-5] }
  func: plot_COP
st_rhcop:
  data:
    - { log: st_allRefWrench, column: [12-17] }
  func: plot_COP
st_lhcop:
  data:
    - { log: st_allRefWrench, column: [17-23] }
  func: plot_COP
rmfo_rhcop:
  data:
    - { log: rmfo_off_rhsensor, column: [0-5] }
  func: plot_COP
rmfo_lhcop:
  data:
    - { log: rmfo_off_lhsensor, column: [0-5] }
  func: plot_COP
# time
time:
  func: plot_time
  data:
    - { log: sh_qOut, column: [0]}
